<H1 style="direction:rtl"><font color="red" face="IRANSans">جلسه هفتم : آموزش کتابخانه numpy</font></H1>

<img src="images/numpy.png" alt="this slowpoke moves"  width="500" />

<H2 style="direction:rtl"><font color="blue" face="IRANSans">معرفی و نصب numpy</font></H2>
<div style="direction:rtl;font-family:vazir;margin:10px 0;" face="IRANSans">
    <ul>
        <li style="margin:3px 0;"> NumPy (Numerical Python) پایه‌ای‌ترین و پرکاربردترین کتابخانه‌ زبان برنامه نویسی پایتون برای محاسبات علمی است.
</li>
        <li style="margin:3px 0;"> با استفاده از این کتابخانه امکان کار با آرایه‌ها و ماتریس‌های بزرگ چند بعدی <b>همگن</b> فراهم می‌شود.
</li>
        <li style="margin:3px 0;"> با استفاده از این کتابخانه می‌توانیم انواع عملیات ریاضی، منطقی، تغییر شکل، مرتب‌سازی، انتخاب و ... را بر روی آرایه‌ها با سرعت بالایی اجرا کنیم.
</li>
        <li style="margin:3px 0;"> همگن: داده در یک آرایه  NumPy باید دارای نوع مشابهی باشند
</li>
        <li style="margin:3px 0;"> با استفاده از دستور <b>pip install</b>  می‌توانیم کتابخانه موردنظرمان را در پایتون نصب کنیم.
</li>
    </ul>
</div>


<img src="images/install.png" alt="this slowpoke moves"  width="1000" />

In [2]:
import numpy
numpy.__version__

'1.23.2'

In [3]:
import numpy as np

<img src="images/array-axis1.png" alt="array axis"  width="800" />

<img src="images/numpy_data_types.png" alt="array axis"  width="500" />

## Creating Arrays from Python Lists

In [4]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [5]:
# float array:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
# float array:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
[i for i in range(10,20)]

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [8]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
#2D array:
np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#3D array:
np.array([
    [[1, 2, 3], 
    [4, 5, 6]],
    [[7, 8, 9], 
    [10, 11, 12]]
    
])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Creating Arrays with numpy functions

In [11]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.09541984, 0.58312801, 0.76309129],
       [0.75735389, 0.66903106, 0.33338845],
       [0.69504856, 0.85249559, 0.29678695]])

In [17]:
# Create a 4x2 array of random integer numbers
# random values between 0 and 1
np.random.randint(1,10,(4,2), dtype=int)

array([[7, 6],
       [5, 2],
       [1, 1],
       [7, 6]])

In [15]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 2.38053576, -1.32631239, -0.55804087],
       [-0.6258745 ,  0.16272027,  1.74019706],
       [-1.2549226 , -0.03289017,  2.01838047]])

## NumPy Array Attributes

In [19]:
x1 = np.random.randint(10, size=6)          # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))     # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes <b>ndim</b> (the number of dimensions), <b>shape</b> (the size of each dimension), <b>size</b> (the total size of the array), and <b>dtype</b> (the data type of the array):

In [20]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype:", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x3 dtype: int32


In [21]:
b = np.array([[1.0,2,3],[4,5,6]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
print("b shape: ",b.shape)
print("b ndim: ",b.ndim)
print("b dtype: ",b.dtype)
print("b size: ",b.size)

b shape:  (2, 3)
b ndim:  2
b dtype:  float64
b size:  6


In [20]:
c = np.array([[1,2,3],[4,5,6j]])
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 0.+6.j]])

In [21]:
print("c shape: ",b.shape)
print("c ndim: ",b.ndim)
print("c dtype: ",b.dtype)
print("c size: ",b.size)

c shape:  (2, 3)
c ndim:  2
c dtype:  float64
c size:  6


In [22]:
d = np.array([[1,2,3],[4,5,6]])
e = np.array([[1,2,3],[4,5,6]])
f = np.array([d,e])
f

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [23]:
print("f shape: ",b.shape)
print("f ndim: ",b.ndim)
print("f dtype: ",b.dtype)
print("f size: ",b.size)

f shape:  (2, 3)
f ndim:  2
f dtype:  float64
f size:  6


In [18]:
print(type(a))
print(type(b))
print(type(c))
print(type(f))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Array Indexing: Accessing Single Elements

In [23]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
print(a[0])
print(a[-3])

1
13


In [25]:
a[1] = 150
a

array([  1, 150,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [27]:
b = np.arange(1,21)
b.shape=(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
b[2]

array([11, 12, 13, 14, 15])

In [29]:
b[2][2]

13

In [30]:
b[2,2]

13

<img src="images/slice.png" alt="array axis"  width="500" />

## Array Slicing: Accessing Subarrays

x[start=0:stop=0:step=0]

### One-dimensional subarrays

In [31]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [33]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [34]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [35]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [36]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Multi-dimensional subarrays

In [5]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[5, 3, 0, 3],
       [2, 0, 5, 0],
       [5, 1, 6, 4]])

In [6]:
x2[:2, :3]  # two rows, three columns

array([[5, 3, 0],
       [2, 0, 5]])

In [7]:
x2[:3, ::2]  # all rows, every other column

array([[5, 0],
       [2, 5],
       [5, 6]])

In [8]:
x2[::-1, ::-1]

array([[4, 6, 1, 5],
       [0, 5, 0, 2],
       [3, 0, 3, 5]])

In [9]:
print(x2[:, 0])  # first column of x2

[5 2 5]


In [10]:
print(x2[0, :])  # first row of x2

[5 3 0 3]


In [11]:
print(x2[0])  # equivalent to x2[0, :]

[5 3 0 3]


In [13]:
# دوتای اول همه این سطرها رو چاپ کن
x2[:,0:2]

array([[5, 3],
       [2, 0],
       [5, 1]])

In [41]:
c = np.random.randint(1,9,size=(2,3,4))
c

array([[[3, 3, 6, 1],
        [3, 7, 6, 1],
        [1, 2, 4, 3]],

       [[7, 8, 1, 2],
        [1, 5, 6, 5],
        [3, 1, 2, 3]]])

In [42]:
c[0]

array([[3, 3, 6, 1],
       [3, 7, 6, 1],
       [1, 2, 4, 3]])

In [43]:
c[0][1]

array([3, 7, 6, 1])

In [44]:
c[0][1][-1]

1

In [32]:
c[1, 1, 2]

2

In [33]:
c[:, :, -2:]

array([[[3, 6],
        [8, 7],
        [2, 7]],

       [[2, 4],
        [2, 3],
        [7, 2]]])

## Get unique values

In [45]:
a=np.random.randint(1,100,size=60)
a

array([20, 77, 83, 74, 53,  4, 96, 82, 82, 42, 79, 36, 89,  6, 14, 43, 84,
       20, 58, 19, 72, 61, 10, 20, 24, 69,  8,  5, 88, 52, 99,  6, 92, 93,
       47, 20,  6, 25, 65, 45, 34, 79, 77, 58, 54,  5, 35, 31, 26,  4, 38,
       60, 25, 66, 79, 88, 96, 51, 75, 12])

In [46]:
a=a.reshape((2,5,6))
a

array([[[20, 77, 83, 74, 53,  4],
        [96, 82, 82, 42, 79, 36],
        [89,  6, 14, 43, 84, 20],
        [58, 19, 72, 61, 10, 20],
        [24, 69,  8,  5, 88, 52]],

       [[99,  6, 92, 93, 47, 20],
        [ 6, 25, 65, 45, 34, 79],
        [77, 58, 54,  5, 35, 31],
        [26,  4, 38, 60, 25, 66],
        [79, 88, 96, 51, 75, 12]]])

In [47]:
unique_array = np.unique(a)
unique_array

array([ 4,  5,  6,  8, 10, 12, 14, 19, 20, 24, 25, 26, 31, 34, 35, 36, 38,
       42, 43, 45, 47, 51, 52, 53, 54, 58, 60, 61, 65, 66, 69, 72, 74, 75,
       77, 79, 82, 83, 84, 88, 89, 92, 93, 96, 99])

## Mask

In [48]:
a[a>30]         # dakhele bracket ebarathaye sharti

array([77, 83, 74, 53, 96, 82, 82, 42, 79, 36, 89, 43, 84, 58, 72, 61, 69,
       88, 52, 99, 92, 93, 47, 65, 45, 34, 79, 77, 58, 54, 35, 31, 38, 60,
       66, 79, 88, 96, 51, 75])

<img src="images/mask.gif" alt="broadcasting"  width="700" />

In [49]:
greater_than_30 = a > 30        # mask    in shart ro emal mikone ruye araye 
greater_than_30

array([[[False,  True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True,  True],
        [ True, False, False,  True,  True, False],
        [ True, False,  True,  True, False, False],
        [False,  True, False, False,  True,  True]],

       [[ True, False,  True,  True,  True, False],
        [False, False,  True,  True,  True,  True],
        [ True,  True,  True, False,  True,  True],
        [False, False,  True,  True, False,  True],
        [ True,  True,  True,  True,  True, False]]])

In [50]:
a[greater_than_30]

array([77, 83, 74, 53, 96, 82, 82, 42, 79, 36, 89, 43, 84, 58, 72, 61, 69,
       88, 52, 99, 92, 93, 47, 65, 45, 34, 79, 77, 58, 54, 35, 31, 38, 60,
       66, 79, 88, 96, 51, 75])

In [52]:
even_elements = a % 2 ==0
even_elements

array([[[ True, False, False,  True, False,  True],
        [ True,  True,  True,  True, False,  True],
        [False,  True,  True, False,  True,  True],
        [ True, False,  True, False,  True,  True],
        [ True, False,  True, False,  True,  True]],

       [[False,  True,  True, False, False,  True],
        [ True, False, False, False,  True, False],
        [False,  True,  True, False, False, False],
        [ True,  True,  True,  True, False,  True],
        [False,  True,  True, False, False,  True]]])

In [54]:
final_mask = np.logical_and(greater_than_30,even_elements)
a[final_mask]

array([74, 96, 82, 82, 42, 36, 84, 58, 72, 88, 52, 92, 34, 58, 54, 38, 60,
       66, 88, 96])

<img src="images/mask.png" alt="array axis"  width="800" />

## Broadcasting

<H3 style="direction:rtl"><font color="blue" face="IRANSans">Broadcasting یا انتشار همگانی در Numpy</font></H3>
<div style="direction:rtl;font-family:vazir;margin:10px 0;" face="IRANSans">
    <ul>
        <li style="margin:3px 0;"> واژه‌ی Broadcasting به چگونگی رفتار Numpy با آرایه‌هایی با Shape متفاوت در خلال عملگرهای محاسباتی اشاره دارد. </li>
        <li style="margin:3px 0;"> به طور خلاصه، آرایه‌ی کوچکتر به اندازه‌ی آرایه‌ی بزرگتر پخش می‌شود تا به شکل و Shape یکسانی با آن تبدیل شود.  </li>
        <li style="margin:3px 0;"><b> قانون Broadcasting</b>: باید اندازه‌ی محور نهایی یا آخر (یا همان مقدار آخرین Shape)، در هر دو آرایه‌ داده‌ یکسان باشد؛ یا مقدار بُعد آخرِ حداقل یکی از آرایه‌ها برابر یک باشد. </li>

</div>




<img src="images/02.05-broadcasting.png" alt="broadcasting"  width="500" />

<img src="images/broadcasting-3d-scalar.gif" alt="broadcasting"  width="500" />

<img src="images/broadcasting-col-row.gif" alt="broadcasting"  width="500" />

In [55]:
# Broadcasting
a= np.arange(5)
a

array([0, 1, 2, 3, 4])

In [56]:
a+4

array([4, 5, 6, 7, 8])

In [57]:
b=np.random.randint(1,9,size=5).reshape((1,5))
b

array([[1, 3, 6, 5, 3]])

In [58]:
a+b

array([[1, 4, 8, 8, 7]])

In [50]:
a-b

array([[-7, -7,  1,  2, -3]])

In [51]:
a*b

array([[ 0,  8,  2,  3, 28]])

In [52]:
a/b

array([[0.        , 0.125     , 2.        , 3.        , 0.57142857]])

In [53]:
a%b

array([[0, 1, 0, 0, 4]], dtype=int32)

In [54]:
a//b

array([[0, 0, 2, 3, 0]], dtype=int32)

In [59]:
c=np.random.randint(1,99,size=50).reshape((5,10))
c

array([[18, 96, 89, 30, 12, 91, 13, 35, 67, 70],
       [48,  3, 17, 98, 37, 23, 39, 46, 22, 10],
       [55, 78, 63, 92, 73, 21,  4,  1, 65, 89],
       [78, 45, 46, 85, 98, 95, 88, 21,  2, 21],
       [20, 57, 43, 83, 74, 40, 37, 81,  2, 80]])

In [61]:
print(b.shape,c.shape)

(1, 5) (5, 10)


In [60]:
b+c

ValueError: operands could not be broadcast together with shapes (1,5) (5,10) 

In [62]:
c=np.random.randint(1,99,size=50).reshape((10,5))
c

array([[68, 70, 62, 74, 85],
       [43, 61, 70, 90, 94],
       [ 5, 53, 63, 78, 61],
       [57, 22, 67, 43, 48],
       [41, 30, 75, 63, 69],
       [89, 84, 60, 34, 80],
       [82, 29, 84, 60, 19],
       [54, 19,  9, 28, 26],
       [ 2, 13,  1, 28, 25],
       [65, 98, 30, 17,  7]])

In [58]:
b+c

array([[ 71,  62,  39,  79,  14],
       [ 73,  10,  64,  42,  33],
       [ 90,  14,  91,   9,  96],
       [ 73,  88,  84,  93,  87],
       [ 85, 104,  22,  50,  59],
       [ 87,  94,  49,  56,  37],
       [ 78,  24,  44,  97,  48],
       [ 40,  85,  70,  85,  86],
       [ 48,  68,  75,  52,  64],
       [ 25,  83,  16,  71, 104]])

In [59]:
d=np.arange(5).reshape(5,1)
d

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [60]:
b+d

array([[ 7,  8,  1,  1,  7],
       [ 8,  9,  2,  2,  8],
       [ 9, 10,  3,  3,  9],
       [10, 11,  4,  4, 10],
       [11, 12,  5,  5, 11]])

In [63]:
e=np.random.randint(1,99,size=40).reshape((2,5,4))
e

array([[[29, 63, 89, 45],
        [96, 31, 37, 36],
        [51, 24, 78,  3],
        [15, 23,  7, 72],
        [92, 10, 58, 22]],

       [[79, 34, 82, 21],
        [28, 15, 42, 19],
        [64, 59, 69, 88],
        [68, 78, 54, 39],
        [12, 53, 53, 41]]])

In [62]:
array = np.arange(20).reshape(5,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [63]:
array+e

array([[[ 59,  82,  79,  53],
        [ 12,  83,  38,  71],
        [ 76,  44,  62,  67],
        [ 58, 103,  30, 106],
        [ 39,  86,  27, 113]],

       [[ 51,   8,  11,  50],
        [ 32,  38,  26,  76],
        [102,  30,  27, 108],
        [ 74, 101,  87,  49],
        [107,  77,  86,  41]]])

## Numpy statistical functions 

In [64]:
np.mean(e)

46.975

In [65]:
np.median(e)

43.5

In [66]:
np.max(e)

96

In [67]:
np.min(e)

3

<img src="images/min-axis.PNG" alt="broadcasting"  width="400" />

In [68]:
np.var(e)     # parakandegi anasor nesbat be miyangin

684.1743749999999

In [69]:
np.std(e)    # enheraf meyar

26.15672714618555

In [70]:
np.sqrt(np.var(e))

26.15672714618555

In [71]:
first_array = np.arange(10) + 1
final = np.sqrt(first_array)
final

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [72]:
np.sum(e)/e.size

46.975

In [73]:
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.any(a)

True

<img src="images/Other-aggregation-functions.PNG" alt="broadcasting"  width="500" />

## Structered Array

In [72]:
names = ["Mohammad","Ali","Hadi","Ehsan"]
ages = [20,15,25,28]
cities = ["tehran", "mashhad",'yazd','tabriz']

In [75]:
pattern = [("name","U50"),("age","i4"),("city","U50")]

<img src="images/dtype.PNG" alt="dtype"  width="400" />

In [76]:
my_array = np.zeros(5, dtype=pattern)
my_array

array([('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [77]:
my_array[0] = ("mohammad",24,"tehran")
my_array

array([('mohammad', 24, 'tehran'), ('',  0, ''), ('',  0, ''),
       ('',  0, ''), ('',  0, '')],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [78]:
my_array[3] = ("ehsan",21,"tabriz")
my_array

array([('mohammad', 24, 'tehran'), ('',  0, ''), ('',  0, ''),
       ('ehsan', 21, 'tabriz'), ('',  0, '')],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [79]:
my_array['age']

array([24,  0,  0, 21,  0])

In [80]:
my_3D_array = np.zeros((2,3,4), dtype=pattern)
my_3D_array

array([[[('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
        [('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
        [('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')]],

       [[('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
        [('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')],
        [('', 0, ''), ('', 0, ''), ('', 0, ''), ('', 0, '')]]],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

In [81]:
my_3D_array[1,1,3] = ("Ali",30,"yazd")
my_3D_array

array([[[('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')],
        [('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')],
        [('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')]],

       [[('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')],
        [('',  0, ''), ('',  0, ''), ('',  0, ''), ('Ali', 30, 'yazd')],
        [('',  0, ''), ('',  0, ''), ('',  0, ''), ('',  0, '')]]],
      dtype=[('name', '<U50'), ('age', '<i4'), ('city', '<U50')])

## Views & Copy

In [82]:
first_array = np.arange(1,25).reshape(2,3,4)
first_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [83]:
second_array = first_array
second_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [84]:
second_array == first_array

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [85]:
first_array is second_array       

True

In [86]:
id(first_array),id(second_array)

(2233947418672, 2233947418672)

In [87]:
first_array[1,0,0] = 100
first_array

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [88]:
second_array

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [89]:
third_array = first_array.view()
third_array

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [90]:
third_array == first_array

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [91]:
third_array is first_array

False

In [92]:
id(third_array), id(first_array)

(2233947420992, 2233947418672)

In [93]:
first_array[0,0,0] = 310
first_array

array([[[310,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [94]:
third_array         

array([[[310,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [95]:
forth_array = np.copy(first_array)            # deep copy
forth_array

array([[[310,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [96]:
forth_array[0,0,1] = 120
forth_array

array([[[310, 120,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [97]:
first_array

array([[[310,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

## Add And Remove Elements From Array

In [98]:
a = np.arange(10)
b = np.append(a, [10, 12])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])

In [99]:
c = np.random.randint(1, 99, size=24).reshape(2, 3, 4)
g = np.random.randint(1, 99, size=24).reshape(2, 3, 4)
d = np.append(c, g, axis=2)
d

array([[[78, 52, 56, 44, 65,  1, 65, 82],
        [ 3,  4, 64, 44, 68, 64, 71, 55],
        [48, 30, 64,  1, 89, 82, 75, 27]],

       [[49, 42, 79, 19, 45, 84, 88, 56],
        [11, 85, 92, 38, 73, 94, 30, 20],
        [70, 35, 68, 86, 17, 92, 36, 75]]])

In [100]:
h = np.insert(c, 2, [1 , 2, 3], axis=2)
h

array([[[78, 52,  1, 56, 44],
        [ 3,  4,  2, 64, 44],
        [48, 30,  3, 64,  1]],

       [[49, 42,  1, 79, 19],
        [11, 85,  2, 92, 38],
        [70, 35,  3, 68, 86]]])

In [101]:
m = np.delete(c, 1, axis=2)
m

array([[[78, 56, 44],
        [ 3, 64, 44],
        [48, 64,  1]],

       [[49, 79, 19],
        [11, 92, 38],
        [70, 68, 86]]])

<img src="images/delete.png" alt="dtype"  width="700" />

## Array Concatenation and Splitting

In [102]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [103]:
a = np.arange(12).reshape((3, 4))
b = np.arange(13, 25).reshape((3, 4))

In [104]:
result0 = np.concatenate((a, b), axis=0)
result0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [105]:
result1 = np.concatenate((a, b), axis=1)
result1

array([[ 0,  1,  2,  3, 13, 14, 15, 16],
       [ 4,  5,  6,  7, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 21, 22, 23, 24]])

In [106]:
e = np.random.randint(1, 99, size=40).reshape(4, 2, 5)
e

array([[[76, 64, 64, 88, 43],
        [31, 73,  3, 84, 50]],

       [[ 2, 70, 39, 90, 11],
        [93, 25, 18, 90, 25]],

       [[12, 75, 75, 22, 89],
        [78, 16, 65, 57,  2]],

       [[82, 94, 92, 34, 58],
        [16, 65, 30, 14, 85]]])

In [107]:
split0 = np.split(e, 4, axis=0)
split1 = np.split(e, 2, axis=1)
split2 = np.split(e, 5, axis=2)

In [109]:
split1

[array([[[76, 64, 64, 88, 43]],
 
        [[ 2, 70, 39, 90, 11]],
 
        [[12, 75, 75, 22, 89]],
 
        [[82, 94, 92, 34, 58]]]), array([[[31, 73,  3, 84, 50]],
 
        [[93, 25, 18, 90, 25]],
 
        [[78, 16, 65, 57,  2]],
 
        [[16, 65, 30, 14, 85]]])]

## Transpose

In [110]:
my_vector = np.arange(6)
my_2D_array = np.arange(12).reshape((3, 4))
my_3D_array = np.arange(24).reshape((2, 3, 4))

In [111]:
my_vector.shape

(6,)

In [112]:
np.transpose(my_vector)

array([0, 1, 2, 3, 4, 5])

In [113]:
my_vector.shape = (1, 6)
my_vector

array([[0, 1, 2, 3, 4, 5]])

In [114]:
my_vector.shape

(1, 6)

In [115]:
np.transpose(my_vector)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [116]:
np.transpose(my_2D_array)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [117]:
result = np.transpose(my_3D_array, axes=(2, 1, 0))
result

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [118]:
my_3D_array.shape, result.shape

((2, 3, 4), (4, 3, 2))

In [119]:
np.swapaxes(my_3D_array, 2, 0).shape

(4, 3, 2)

In [120]:
moved = np.moveaxis(my_3D_array, 2, 0)
moved

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [121]:
moved.shape, my_3D_array.shape

((4, 2, 3), (2, 3, 4))

## Dot Product

<img src="images/maxresdefault.jpg" alt="dtype"  width="800" />

In [122]:
a = np.random.randint(0, 99, size=(3, 4))
b = np.random.randint(0, 99, size=(3, 4))

In [123]:
a

array([[78, 62, 15, 79],
       [70, 13, 19, 92],
       [82, 59, 91,  7]])

In [124]:
b

array([[14, 58, 60,  5],
       [50, 97, 62, 17],
       [80, 12, 36, 70]])

In [125]:
a * b

array([[1092, 3596,  900,  395],
       [3500, 1261, 1178, 1564],
       [6560,  708, 3276,  490]])

In [126]:
c = np.dot(a, b.T)
c

array([[ 5983, 12187, 13054],
       [ 3334,  7503, 12880],
       [10065, 15584, 11034]])

## Tile & Repeat

In [129]:
a = np.arange(10)
b = np.arange(12).reshape((3, 4))

In [130]:
np.tile(a, 3).reshape(3, a.size)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [132]:
np.tile(a, (3, 2, 2))

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [133]:
np.tile(b, 3)

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11]])

In [134]:
np.repeat(a, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

In [135]:
np.repeat(b, 2, axis=1)

array([[ 0,  0,  1,  1,  2,  2,  3,  3],
       [ 4,  4,  5,  5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10, 10, 11, 11]])

<img src="images/tile-repeat.PNG" alt="dtype"  width="500" />

## Sort Arrays

<img src="images/sort.PNG" alt="dtype"  width="500" />

In [136]:
c = np.random.randint(99, size=10)
d = np.random.randint(99, size=(3, 4))

In [138]:
c

array([72, 42,  4, 68, 68, 93, 76, 47, 30, 16])

In [139]:
d

array([[41, 22, 30, 62],
       [72, 23, 73, 67],
       [53, 22, 54, 24]])

In [140]:
np.sort(c)

array([ 4, 16, 30, 42, 47, 68, 68, 72, 76, 93])

<img src="images/sort-example.PNG" alt="dtype"  width="500" />

In [141]:
np.sort(d, axis=0)

array([[41, 22, 30, 24],
       [53, 22, 54, 62],
       [72, 23, 73, 67]])

In [143]:
c

array([72, 42,  4, 68, 68, 93, 76, 47, 30, 16])

In [142]:
np.argsort(c)

array([2, 9, 8, 1, 7, 3, 4, 0, 6, 5], dtype=int64)

In [139]:
np.argsort(d, axis=0)

array([[1, 1, 1, 2],
       [0, 2, 0, 0],
       [2, 0, 2, 1]], dtype=int64)

In [140]:
np.argmax(c)

4

In [141]:
np.argmin(c)

3

In [157]:
np.argmax(d, axis=0)

array([1, 1, 1, 1], dtype=int64)

## Padding

<img src="images/padding.PNG" alt="dtype"  width="700" />

<img src="images/Convolution_arithmetic_-_Full_padding_no_strides.gif" alt="dtype"  width="700" />


## Speed Test

In [144]:
import datetime

In [ ]:
a = np.random.randint(10, 99, size=100000, dtype=np.int64)
b = np.random.randint(10, 99, size=100000, dtype=np.int64)

In [154]:
python_start = datetime.datetime.now()
python_sum = 0
for i, j in zip(a,b):
    python_sum += i*j
python_end = datetime.datetime.now()
python_result = python_end - python_start
python_sum, python_result

(2919872859, datetime.timedelta(microseconds=829523))

In [155]:
numpy_start = datetime.datetime.now()
numpy_sum = np.dot(a, b)
numpy_end = datetime.datetime.now()
numpy_result = numpy_end - numpy_start
numpy_sum, numpy_result

(2919872859, datetime.timedelta(microseconds=1994))

In [156]:
python_result / numpy_result

416.00952858575727

## RGB Images

<img src="images/rgb.PNG" alt="dtype"  width="800" />

## For further reading

https://numpy.org/doc/stable/reference/